import * as install_absolute_orientation_sensor from "../api/device/members/absolute-orientation-sensor.js";
import * as install_accelerometer from "../api/device/members/accelerometer.js";
import { install as install_device_motion_event_acceleration_including_gravity_property } from "../api/device/members/device-motion-event-acceleration-including-gravity-property.js";
import { install as install_device_motion_event_acceleration_property } from "../api/device/members/device-motion-event-acceleration-property.js";
import { install as install_device_motion_event_acceleration_x_property } from "../api/device/members/device-motion-event-acceleration-x-property.js";
import { install as install_device_motion_event_acceleration_y_property } from "../api/device/members/device-motion-event-acceleration-y-property.js";
import { install as install_device_motion_event_acceleration_z_property } from "../api/device/members/device-motion-event-acceleration-z-property.js";
import * as install_device_motion_event_acceleration from "../api/device/members/device-motion-event-acceleration.js";
import { install as install_device_motion_event_interval_property } from "../api/device/members/device-motion-event-interval-property.js";
import { install as install_device_motion_event_rotation_rate_alpha_property } from "../api/device/members/device-motion-event-rotation-rate-alpha-property.js";
import { install as install_device_motion_event_rotation_rate_beta_property } from "../api/device/members/device-motion-event-rotation-rate-beta-property.js";
import { install as install_device_motion_event_rotation_rate_gamma_property } from "../api/device/members/device-motion-event-rotation-rate-gamma-property.js";
import { install as install_device_motion_event_rotation_rate_property } from "../api/device/members/device-motion-event-rotation-rate-property.js";
import * as install_device_motion_event_rotation_rate from "../api/device/members/device-motion-event-rotation-rate.js";
import * as install_device_motion_event from "../api/device/members/device-motion-event.js";
import { install as install_device_orientation_event_absolute_property } from "../api/device/members/device-orientation-event-absolute-property.js";
import { install as install_device_orientation_event_alpha_property } from "../api/device/members/device-orientation-event-alpha-property.js";
import { install as install_device_orientation_event_beta_property } from "../api/device/members/device-orientation-event-beta-property.js";
import { install as install_device_orientation_event_gamma_property } from "../api/device/members/device-orientation-event-gamma-property.js";
import * as install_device_orientation_event from "../api/device/members/device-orientation-event.js";
import * as install_gamepad_button from "../api/device/members/gamepad-button.js";
import { install as install_gamepad_event_gamepad_property } from "../api/device/members/gamepad-event-gamepad-property.js";
import * as install_gamepad_event from "../api/device/members/gamepad-event.js";
import * as install_gamepad_haptic_actuator from "../api/device/members/gamepad-haptic-actuator.js";
import * as install_gamepad from "../api/device/members/gamepad.js";
import * as install_geolocation_coordinates from "../api/device/members/geolocation-coordinates.js";
import * as install_geolocation_position_error from "../api/device/members/geolocation-position-error.js";
import * as install_geolocation_position from "../api/device/members/geolocation-position.js";
import * as install_geolocation from "../api/device/members/geolocation.js";
import * as install_gravity_sensor from "../api/device/members/gravity-sensor.js";
import * as install_gyroscope from "../api/device/members/gyroscope.js";
import * as install_linear_acceleration_sensor from "../api/device/members/linear-acceleration-sensor.js";
import * as install_orientation_sensor from "../api/device/members/orientation-sensor.js";
import * as install_relative_orientation_sensor from "../api/device/members/relative-orientation-sensor.js";
import { install as install_sensor_error_event_error_property } from "../api/device/members/sensor-error-event-error-property.js";
import * as install_sensor_error_event from "../api/device/members/sensor-error-event.js";
import * as install_sensor from "../api/device/members/sensor.js";

export function installDeviceAPIs() {
  install_geolocation_position_error.installGlobal();
  install_geolocation_position.installGlobal();
  install_geolocation_coordinates.installGlobal();
  install_geolocation.installGlobal();
  install_gamepad_haptic_actuator.installGlobal();
  install_gamepad_event.installGlobal();
  install_gamepad_button.installGlobal();
  install_gamepad.installGlobal();
  install_sensor.installGlobal();
  install_sensor_error_event.installGlobal();
  install_accelerometer.installGlobal();
  install_gravity_sensor.installGlobal();
  install_linear_acceleration_sensor.installGlobal();
  install_gyroscope.installGlobal();
  install_orientation_sensor.installGlobal();
  install_absolute_orientation_sensor.installGlobal();
  install_relative_orientation_sensor.installGlobal();
  install_device_motion_event.installGlobal();
  install_device_motion_event_acceleration.installGlobal();
  install_device_motion_event_rotation_rate.installGlobal();
  install_device_orientation_event.installGlobal();
  install_geolocation_position_error.installRelation();
  install_geolocation_position.installRelation();
  install_geolocation_coordinates.installRelation();
  install_geolocation.installRelation();
  install_gamepad_haptic_actuator.installRelation();
  install_gamepad_event.installRelation();
  install_gamepad_button.installRelation();
  install_gamepad.installRelation();
  install_sensor.installRelation();
  install_sensor_error_event.installRelation();
  install_accelerometer.installRelation();
  install_gravity_sensor.installRelation();
  install_linear_acceleration_sensor.installRelation();
  install_gyroscope.installRelation();
  install_orientation_sensor.installRelation();
  install_absolute_orientation_sensor.installRelation();
  install_relative_orientation_sensor.installRelation();
  install_device_motion_event.installRelation();
  install_device_motion_event_acceleration.installRelation();
  install_device_motion_event_rotation_rate.installRelation();
  install_device_orientation_event.installRelation();
  install_geolocation_position_error.installOwnedMember0();
  install_geolocation_position_error.installOwnedMember1();
  install_geolocation_position_error.installConstant0();
  install_geolocation_position_error.installConstant1();
  install_geolocation_position_error.installConstant2();
  install_geolocation_position_error.installConstructorBacklink();
  install_geolocation_position_error.installTag();
  install_geolocation_position.installOwnedMember0();
  install_geolocation_position.installOwnedMember1();
  install_geolocation_position.installOwnedMember2();
  install_geolocation_position.installConstructorBacklink();
  install_geolocation_position.installTag();
  install_geolocation_coordinates.installOwnedMember0();
  install_geolocation_coordinates.installOwnedMember1();
  install_geolocation_coordinates.installOwnedMember2();
  install_geolocation_coordinates.installOwnedMember3();
  install_geolocation_coordinates.installOwnedMember4();
  install_geolocation_coordinates.installOwnedMember5();
  install_geolocation_coordinates.installOwnedMember6();
  install_geolocation_coordinates.installOwnedMember7();
  install_geolocation_coordinates.installConstructorBacklink();
  install_geolocation_coordinates.installTag();
  install_geolocation.installOwnedMember0();
  install_geolocation.installOwnedMember1();
  install_geolocation.installOwnedMember2();
  install_geolocation.installConstructorBacklink();
  install_geolocation.installTag();
  install_gamepad_haptic_actuator.installOwnedMember0();
  install_gamepad_haptic_actuator.installOwnedMember1();
  install_gamepad_haptic_actuator.installOwnedMember2();
  install_gamepad_haptic_actuator.installOwnedMember3();
  install_gamepad_haptic_actuator.installConstructorBacklink();
  install_gamepad_haptic_actuator.installTag();
  install_gamepad_event_gamepad_property();
  install_gamepad_event.installConstructorBacklink();
  install_gamepad_event.installTag();
  install_gamepad_button.installOwnedMember0();
  install_gamepad_button.installOwnedMember1();
  install_gamepad_button.installOwnedMember2();
  install_gamepad_button.installConstructorBacklink();
  install_gamepad_button.installTag();
  install_gamepad.installOwnedMember0();
  install_gamepad.installOwnedMember1();
  install_gamepad.installOwnedMember2();
  install_gamepad.installOwnedMember3();
  install_gamepad.installOwnedMember4();
  install_gamepad.installOwnedMember5();
  install_gamepad.installOwnedMember6();
  install_gamepad.installOwnedMember7();
  install_gamepad.installConstructorBacklink();
  install_gamepad.installTag();
  install_sensor.installOwnedMember0();
  install_sensor.installOwnedMember1();
  install_sensor.installOwnedMember2();
  install_sensor.installOwnedMember3();
  install_sensor.installOwnedMember4();
  install_sensor.installOwnedMember5();
  install_sensor.installOwnedMember6();
  install_sensor.installOwnedMember7();
  install_sensor.installConstructorBacklink();
  install_sensor.installTag();
  install_sensor_error_event_error_property();
  install_sensor_error_event.installConstructorBacklink();
  install_sensor_error_event.installTag();
  install_accelerometer.installOwnedMember0();
  install_accelerometer.installOwnedMember1();
  install_accelerometer.installOwnedMember2();
  install_accelerometer.installConstructorBacklink();
  install_accelerometer.installTag();
  install_gravity_sensor.installConstructorBacklink();
  install_gravity_sensor.installTag();
  install_linear_acceleration_sensor.installConstructorBacklink();
  install_linear_acceleration_sensor.installTag();
  install_gyroscope.installOwnedMember0();
  install_gyroscope.installOwnedMember1();
  install_gyroscope.installOwnedMember2();
  install_gyroscope.installConstructorBacklink();
  install_gyroscope.installTag();
  install_orientation_sensor.installOwnedMember0();
  install_orientation_sensor.installOwnedMember1();
  install_orientation_sensor.installConstructorBacklink();
  install_orientation_sensor.installTag();
  install_absolute_orientation_sensor.installConstructorBacklink();
  install_absolute_orientation_sensor.installTag();
  install_relative_orientation_sensor.installConstructorBacklink();
  install_relative_orientation_sensor.installTag();
  install_device_motion_event_acceleration_property();
  install_device_motion_event_acceleration_including_gravity_property();
  install_device_motion_event_rotation_rate_property();
  install_device_motion_event_interval_property();
  install_device_motion_event.installConstructorBacklink();
  install_device_motion_event.installTag();
  install_device_motion_event_acceleration_x_property();
  install_device_motion_event_acceleration_y_property();
  install_device_motion_event_acceleration_z_property();
  install_device_motion_event_acceleration.installConstructorBacklink();
  install_device_motion_event_acceleration.installTag();
  install_device_motion_event_rotation_rate_alpha_property();
  install_device_motion_event_rotation_rate_beta_property();
  install_device_motion_event_rotation_rate_gamma_property();
  install_device_motion_event_rotation_rate.installConstructorBacklink();
  install_device_motion_event_rotation_rate.installTag();
  install_device_orientation_event_alpha_property();
  install_device_orientation_event_beta_property();
  install_device_orientation_event_gamma_property();
  install_device_orientation_event_absolute_property();
  install_device_orientation_event.installConstructorBacklink();
  install_device_orientation_event.installTag();
}
