// Generated by tools/generate-speech-surface.mjs.
// Source: captured Edge 150 interface evidence.
// Do not edit by hand.

export const SPEECH_SURFACES = Object.freeze({
  "SpeechSynthesis": {
    "constructorParent": "EventTarget",
    "prototypeParent": "EventTarget",
    "members": [
      [
        "accessor",
        "pending"
      ],
      [
        "accessor",
        "speaking"
      ],
      [
        "accessor",
        "paused"
      ],
      [
        "accessor",
        "onvoiceschanged"
      ],
      [
        "method",
        "cancel",
        0
      ],
      [
        "method",
        "getVoices",
        0
      ],
      [
        "method",
        "pause",
        0
      ],
      [
        "method",
        "resume",
        0
      ],
      [
        "method",
        "speak",
        1
      ],
      [
        "method",
        "preload",
        2
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "SpeechSynthesisErrorEvent": {
    "constructorParent": "SpeechSynthesisEvent",
    "prototypeParent": "SpeechSynthesisEvent",
    "members": [
      [
        "accessor",
        "error"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "SpeechSynthesisEvent": {
    "constructorParent": "Event",
    "prototypeParent": "Event",
    "members": [
      [
        "accessor",
        "utterance"
      ],
      [
        "accessor",
        "charIndex"
      ],
      [
        "accessor",
        "charLength"
      ],
      [
        "accessor",
        "elapsedTime"
      ],
      [
        "accessor",
        "name"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "SpeechSynthesisUtterance": {
    "constructorParent": "EventTarget",
    "prototypeParent": "EventTarget",
    "members": [
      [
        "accessor",
        "text"
      ],
      [
        "accessor",
        "lang"
      ],
      [
        "accessor",
        "voice"
      ],
      [
        "accessor",
        "volume"
      ],
      [
        "accessor",
        "rate"
      ],
      [
        "accessor",
        "pitch"
      ],
      [
        "accessor",
        "onstart"
      ],
      [
        "accessor",
        "onend"
      ],
      [
        "accessor",
        "onerror"
      ],
      [
        "accessor",
        "onpause"
      ],
      [
        "accessor",
        "onresume"
      ],
      [
        "accessor",
        "onmark"
      ],
      [
        "accessor",
        "onboundary"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "SpeechSynthesisVoice": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "voiceURI"
      ],
      [
        "accessor",
        "name"
      ],
      [
        "accessor",
        "lang"
      ],
      [
        "accessor",
        "localService"
      ],
      [
        "accessor",
        "default"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  }
});
