// Generated by tools/generate-audio-surface.mjs.
// Source: captured Edge 150 interface evidence.
// Do not edit by hand.

export const AUDIO_SURFACES = Object.freeze({
  "BaseAudioContext": {
    "constructorParent": "EventTarget",
    "prototypeParent": "EventTarget",
    "members": [
      [
        "accessor",
        "destination"
      ],
      [
        "accessor",
        "sampleRate"
      ],
      [
        "accessor",
        "currentTime"
      ],
      [
        "accessor",
        "listener"
      ],
      [
        "accessor",
        "state"
      ],
      [
        "accessor",
        "onstatechange"
      ],
      [
        "method",
        "createAnalyser",
        0
      ],
      [
        "method",
        "createBiquadFilter",
        0
      ],
      [
        "method",
        "createBuffer",
        3
      ],
      [
        "method",
        "createBufferSource",
        0
      ],
      [
        "method",
        "createChannelMerger",
        0
      ],
      [
        "method",
        "createChannelSplitter",
        0
      ],
      [
        "method",
        "createConstantSource",
        0
      ],
      [
        "method",
        "createConvolver",
        0
      ],
      [
        "method",
        "createDelay",
        0
      ],
      [
        "method",
        "createDynamicsCompressor",
        0
      ],
      [
        "method",
        "createGain",
        0
      ],
      [
        "method",
        "createIIRFilter",
        2
      ],
      [
        "method",
        "createOscillator",
        0
      ],
      [
        "method",
        "createPanner",
        0
      ],
      [
        "method",
        "createPeriodicWave",
        2
      ],
      [
        "method",
        "createScriptProcessor",
        0
      ],
      [
        "method",
        "createStereoPanner",
        0
      ],
      [
        "method",
        "createWaveShaper",
        0
      ],
      [
        "method",
        "decodeAudioData",
        1
      ],
      [
        "constructor"
      ],
      [
        "accessor",
        "audioWorklet"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioContext": {
    "constructorParent": "BaseAudioContext",
    "prototypeParent": "BaseAudioContext",
    "members": [
      [
        "accessor",
        "baseLatency"
      ],
      [
        "accessor",
        "outputLatency"
      ],
      [
        "accessor",
        "onerror"
      ],
      [
        "method",
        "close",
        0
      ],
      [
        "method",
        "createMediaElementSource",
        1
      ],
      [
        "method",
        "createMediaStreamDestination",
        0
      ],
      [
        "method",
        "createMediaStreamSource",
        1
      ],
      [
        "method",
        "getOutputTimestamp",
        0
      ],
      [
        "method",
        "resume",
        0
      ],
      [
        "method",
        "suspend",
        0
      ],
      [
        "accessor",
        "playbackStats"
      ],
      [
        "constructor"
      ],
      [
        "accessor",
        "sinkId"
      ],
      [
        "accessor",
        "onsinkchange"
      ],
      [
        "method",
        "setSinkId",
        1
      ],
      [
        "tag"
      ]
    ]
  },
  "OfflineAudioContext": {
    "constructorParent": "BaseAudioContext",
    "prototypeParent": "BaseAudioContext",
    "members": [
      [
        "accessor",
        "oncomplete"
      ],
      [
        "accessor",
        "length"
      ],
      [
        "method",
        "resume",
        0
      ],
      [
        "method",
        "startRendering",
        0
      ],
      [
        "method",
        "suspend",
        1
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioBuffer": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "length"
      ],
      [
        "accessor",
        "duration"
      ],
      [
        "accessor",
        "sampleRate"
      ],
      [
        "accessor",
        "numberOfChannels"
      ],
      [
        "method",
        "copyFromChannel",
        2
      ],
      [
        "method",
        "copyToChannel",
        2
      ],
      [
        "method",
        "getChannelData",
        1
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioNode": {
    "constructorParent": "EventTarget",
    "prototypeParent": "EventTarget",
    "members": [
      [
        "accessor",
        "context"
      ],
      [
        "accessor",
        "numberOfInputs"
      ],
      [
        "accessor",
        "numberOfOutputs"
      ],
      [
        "accessor",
        "channelCount"
      ],
      [
        "accessor",
        "channelCountMode"
      ],
      [
        "accessor",
        "channelInterpretation"
      ],
      [
        "method",
        "connect",
        1
      ],
      [
        "method",
        "disconnect",
        0
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioDestinationNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "maxChannelCount"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioListener": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "positionX"
      ],
      [
        "accessor",
        "positionY"
      ],
      [
        "accessor",
        "positionZ"
      ],
      [
        "accessor",
        "forwardX"
      ],
      [
        "accessor",
        "forwardY"
      ],
      [
        "accessor",
        "forwardZ"
      ],
      [
        "accessor",
        "upX"
      ],
      [
        "accessor",
        "upY"
      ],
      [
        "accessor",
        "upZ"
      ],
      [
        "method",
        "setOrientation",
        6
      ],
      [
        "method",
        "setPosition",
        3
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioParam": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "value"
      ],
      [
        "accessor",
        "automationRate"
      ],
      [
        "accessor",
        "defaultValue"
      ],
      [
        "accessor",
        "minValue"
      ],
      [
        "accessor",
        "maxValue"
      ],
      [
        "method",
        "cancelAndHoldAtTime",
        1
      ],
      [
        "method",
        "cancelScheduledValues",
        1
      ],
      [
        "method",
        "exponentialRampToValueAtTime",
        2
      ],
      [
        "method",
        "linearRampToValueAtTime",
        2
      ],
      [
        "method",
        "setTargetAtTime",
        3
      ],
      [
        "method",
        "setValueAtTime",
        2
      ],
      [
        "method",
        "setValueCurveAtTime",
        3
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioScheduledSourceNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "onended"
      ],
      [
        "method",
        "start",
        0
      ],
      [
        "method",
        "stop",
        0
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioBufferSourceNode": {
    "constructorParent": "AudioScheduledSourceNode",
    "prototypeParent": "AudioScheduledSourceNode",
    "members": [
      [
        "accessor",
        "buffer"
      ],
      [
        "accessor",
        "playbackRate"
      ],
      [
        "accessor",
        "detune"
      ],
      [
        "accessor",
        "loop"
      ],
      [
        "accessor",
        "loopStart"
      ],
      [
        "accessor",
        "loopEnd"
      ],
      [
        "method",
        "start",
        0
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioWorkletNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "parameters"
      ],
      [
        "accessor",
        "port"
      ],
      [
        "accessor",
        "onprocessorerror"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "MediaElementAudioSourceNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "mediaElement"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "MediaStreamAudioSourceNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "mediaStream"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "MediaStreamAudioDestinationNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "stream"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioParamMap": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "size"
      ],
      [
        "method",
        "entries",
        0
      ],
      [
        "method",
        "forEach",
        1
      ],
      [
        "method",
        "get",
        1
      ],
      [
        "method",
        "has",
        1
      ],
      [
        "method",
        "keys",
        0
      ],
      [
        "method",
        "values",
        0
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ],
      [
        "iterator",
        "entries",
        0
      ]
    ]
  },
  "AudioSinkInfo": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "type"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AudioPlaybackStats": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "accessor",
        "underrunDuration"
      ],
      [
        "accessor",
        "underrunEvents"
      ],
      [
        "accessor",
        "totalDuration"
      ],
      [
        "accessor",
        "averageLatency"
      ],
      [
        "accessor",
        "minimumLatency"
      ],
      [
        "accessor",
        "maximumLatency"
      ],
      [
        "method",
        "resetLatency",
        0
      ],
      [
        "method",
        "toJSON",
        0
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "OfflineAudioCompletionEvent": {
    "constructorParent": "Event",
    "prototypeParent": "Event",
    "members": [
      [
        "accessor",
        "renderedBuffer"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "AnalyserNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "fftSize"
      ],
      [
        "accessor",
        "frequencyBinCount"
      ],
      [
        "accessor",
        "minDecibels"
      ],
      [
        "accessor",
        "maxDecibels"
      ],
      [
        "accessor",
        "smoothingTimeConstant"
      ],
      [
        "method",
        "getByteFrequencyData",
        1
      ],
      [
        "method",
        "getByteTimeDomainData",
        1
      ],
      [
        "method",
        "getFloatFrequencyData",
        1
      ],
      [
        "method",
        "getFloatTimeDomainData",
        1
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "BiquadFilterNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "type"
      ],
      [
        "accessor",
        "frequency"
      ],
      [
        "accessor",
        "detune"
      ],
      [
        "accessor",
        "Q"
      ],
      [
        "accessor",
        "gain"
      ],
      [
        "method",
        "getFrequencyResponse",
        3
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "ChannelMergerNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "ChannelSplitterNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "ConstantSourceNode": {
    "constructorParent": "AudioScheduledSourceNode",
    "prototypeParent": "AudioScheduledSourceNode",
    "members": [
      [
        "accessor",
        "offset"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "ConvolverNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "buffer"
      ],
      [
        "accessor",
        "normalize"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "DelayNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "delayTime"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "DynamicsCompressorNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "threshold"
      ],
      [
        "accessor",
        "knee"
      ],
      [
        "accessor",
        "ratio"
      ],
      [
        "accessor",
        "reduction"
      ],
      [
        "accessor",
        "attack"
      ],
      [
        "accessor",
        "release"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "GainNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "gain"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "IIRFilterNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "method",
        "getFrequencyResponse",
        3
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "OscillatorNode": {
    "constructorParent": "AudioScheduledSourceNode",
    "prototypeParent": "AudioScheduledSourceNode",
    "members": [
      [
        "accessor",
        "type"
      ],
      [
        "accessor",
        "frequency"
      ],
      [
        "accessor",
        "detune"
      ],
      [
        "method",
        "setPeriodicWave",
        1
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "PannerNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "panningModel"
      ],
      [
        "accessor",
        "positionX"
      ],
      [
        "accessor",
        "positionY"
      ],
      [
        "accessor",
        "positionZ"
      ],
      [
        "accessor",
        "orientationX"
      ],
      [
        "accessor",
        "orientationY"
      ],
      [
        "accessor",
        "orientationZ"
      ],
      [
        "accessor",
        "distanceModel"
      ],
      [
        "accessor",
        "refDistance"
      ],
      [
        "accessor",
        "maxDistance"
      ],
      [
        "accessor",
        "rolloffFactor"
      ],
      [
        "accessor",
        "coneInnerAngle"
      ],
      [
        "accessor",
        "coneOuterAngle"
      ],
      [
        "accessor",
        "coneOuterGain"
      ],
      [
        "method",
        "setOrientation",
        3
      ],
      [
        "method",
        "setPosition",
        3
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "PeriodicWave": {
    "constructorParent": "",
    "prototypeParent": "Object",
    "members": [
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "ScriptProcessorNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "onaudioprocess"
      ],
      [
        "accessor",
        "bufferSize"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "StereoPannerNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "pan"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  },
  "WaveShaperNode": {
    "constructorParent": "AudioNode",
    "prototypeParent": "AudioNode",
    "members": [
      [
        "accessor",
        "curve"
      ],
      [
        "accessor",
        "oversample"
      ],
      [
        "constructor"
      ],
      [
        "tag"
      ]
    ]
  }
});
