import * as install_rtc_certificate from "../api/webrtc/members/rtc-certificate.js";
import { install as install_rtc_data_channel_event_channel_property } from "../api/webrtc/members/rtc-data-channel-event-channel-property.js";
import * as install_rtc_data_channel_event from "../api/webrtc/members/rtc-data-channel-event.js";
import * as install_rtc_data_channel from "../api/webrtc/members/rtc-data-channel.js";
import * as install_rtc_dtls_transport from "../api/webrtc/members/rtc-dtls-transport.js";
import * as install_rtc_dtmf_sender from "../api/webrtc/members/rtc-dtmf-sender.js";
import { install as install_rtc_dtmf_tone_change_event_tone_property } from "../api/webrtc/members/rtc-dtmf-tone-change-event-tone-property.js";
import * as install_rtc_dtmf_tone_change_event from "../api/webrtc/members/rtc-dtmf-tone-change-event.js";
import * as install_rtc_encoded_audio_frame from "../api/webrtc/members/rtc-encoded-audio-frame.js";
import * as install_rtc_encoded_video_frame from "../api/webrtc/members/rtc-encoded-video-frame.js";
import { install as install_rtc_error_event_error_property } from "../api/webrtc/members/rtc-error-event-error-property.js";
import * as install_rtc_error_event from "../api/webrtc/members/rtc-error-event.js";
import * as install_rtc_error from "../api/webrtc/members/rtc-error.js";
import * as install_rtc_ice_candidate from "../api/webrtc/members/rtc-ice-candidate.js";
import * as install_rtc_ice_transport from "../api/webrtc/members/rtc-ice-transport.js";
import { install as install_rtc_peer_connection_ice_error_event_address_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-address-property.js";
import { install as install_rtc_peer_connection_ice_error_event_error_code_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-error-code-property.js";
import { install as install_rtc_peer_connection_ice_error_event_error_text_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-error-text-property.js";
import { install as install_rtc_peer_connection_ice_error_event_host_candidate_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-host-candidate-property.js";
import { install as install_rtc_peer_connection_ice_error_event_port_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-port-property.js";
import { install as install_rtc_peer_connection_ice_error_event_url_property } from "../api/webrtc/members/rtc-peer-connection-ice-error-event-url-property.js";
import * as install_rtc_peer_connection_ice_error_event from "../api/webrtc/members/rtc-peer-connection-ice-error-event.js";
import { install as install_rtc_peer_connection_ice_event_candidate_property } from "../api/webrtc/members/rtc-peer-connection-ice-event-candidate-property.js";
import * as install_rtc_peer_connection_ice_event from "../api/webrtc/members/rtc-peer-connection-ice-event.js";
import * as install_rtc_peer_connection from "../api/webrtc/members/rtc-peer-connection.js";
import * as install_rtc_rtp_receiver from "../api/webrtc/members/rtc-rtp-receiver.js";
import * as install_rtc_rtp_script_transform from "../api/webrtc/members/rtc-rtp-script-transform.js";
import * as install_rtc_rtp_sender from "../api/webrtc/members/rtc-rtp-sender.js";
import * as install_rtc_rtp_transceiver from "../api/webrtc/members/rtc-rtp-transceiver.js";
import * as install_rtc_sctp_transport from "../api/webrtc/members/rtc-sctp-transport.js";
import * as install_rtc_session_description from "../api/webrtc/members/rtc-session-description.js";
import * as install_rtc_stats_report from "../api/webrtc/members/rtc-stats-report.js";
import { install as install_rtc_track_event_receiver_property } from "../api/webrtc/members/rtc-track-event-receiver-property.js";
import { install as install_rtc_track_event_streams_property } from "../api/webrtc/members/rtc-track-event-streams-property.js";
import { install as install_rtc_track_event_track_property } from "../api/webrtc/members/rtc-track-event-track-property.js";
import { install as install_rtc_track_event_transceiver_property } from "../api/webrtc/members/rtc-track-event-transceiver-property.js";
import * as install_rtc_track_event from "../api/webrtc/members/rtc-track-event.js";
import * as install_webkit_rtc_peer_connection from "../api/webrtc/members/webkit-rtc-peer-connection.js";
import * as webrtcRuntime from "../api/webrtc/webrtc-runtime.js";
import {
  installDispatchedStaticMethod,
} from "../../engine/webidl/dispatched-surface-install.js";

export function installWebRTC() {
  install_rtc_track_event.installGlobal();
  install_rtc_stats_report.installGlobal();
  install_rtc_session_description.installGlobal();
  install_rtc_sctp_transport.installGlobal();
  install_rtc_rtp_transceiver.installGlobal();
  install_rtc_rtp_sender.installGlobal();
  install_rtc_rtp_receiver.installGlobal();
  install_rtc_peer_connection_ice_event.installGlobal();
  install_rtc_peer_connection_ice_error_event.installGlobal();
  install_rtc_peer_connection.installGlobal();
  install_rtc_ice_transport.installGlobal();
  install_rtc_ice_candidate.installGlobal();
  install_rtc_error_event.installGlobal();
  install_rtc_error.installGlobal();
  install_rtc_encoded_video_frame.installGlobal();
  install_rtc_encoded_audio_frame.installGlobal();
  install_rtc_dtls_transport.installGlobal();
  install_rtc_data_channel_event.installGlobal();
  install_rtc_dtmf_tone_change_event.installGlobal();
  install_rtc_dtmf_sender.installGlobal();
  install_rtc_certificate.installGlobal();
  install_rtc_data_channel.installGlobal();
  install_rtc_rtp_script_transform.installGlobal();
  install_rtc_track_event.installRelation();
  install_rtc_stats_report.installRelation();
  install_rtc_session_description.installRelation();
  install_rtc_sctp_transport.installRelation();
  install_rtc_rtp_transceiver.installRelation();
  install_rtc_rtp_sender.installRelation();
  install_rtc_rtp_receiver.installRelation();
  install_rtc_peer_connection_ice_event.installRelation();
  install_rtc_peer_connection_ice_error_event.installRelation();
  install_rtc_peer_connection.installRelation();
  install_rtc_ice_transport.installRelation();
  install_rtc_ice_candidate.installRelation();
  install_rtc_error_event.installRelation();
  install_rtc_error.installRelation();
  install_rtc_encoded_video_frame.installRelation();
  install_rtc_encoded_audio_frame.installRelation();
  install_rtc_dtls_transport.installRelation();
  install_rtc_data_channel_event.installRelation();
  install_rtc_dtmf_tone_change_event.installRelation();
  install_rtc_dtmf_sender.installRelation();
  install_rtc_certificate.installRelation();
  install_rtc_data_channel.installRelation();
  install_rtc_rtp_script_transform.installRelation();
  install_rtc_track_event_receiver_property();
  install_rtc_track_event_track_property();
  install_rtc_track_event_streams_property();
  install_rtc_track_event_transceiver_property();
  install_rtc_track_event.installConstructorBacklink();
  install_rtc_track_event.installTag();
  install_rtc_stats_report.installOwnedMember0();
  install_rtc_stats_report.installOwnedMember1();
  install_rtc_stats_report.installOwnedMember2();
  install_rtc_stats_report.installOwnedMember3();
  install_rtc_stats_report.installOwnedMember4();
  install_rtc_stats_report.installOwnedMember5();
  install_rtc_stats_report.installOwnedMember6();
  install_rtc_stats_report.installConstructorBacklink();
  install_rtc_stats_report.installTag();
  install_rtc_stats_report.installIterator();
  install_rtc_session_description.installOwnedMember0();
  install_rtc_session_description.installOwnedMember1();
  install_rtc_session_description.installOwnedMember2();
  install_rtc_session_description.installConstructorBacklink();
  install_rtc_session_description.installTag();
  install_rtc_sctp_transport.installOwnedMember0();
  install_rtc_sctp_transport.installOwnedMember1();
  install_rtc_sctp_transport.installOwnedMember2();
  install_rtc_sctp_transport.installOwnedMember3();
  install_rtc_sctp_transport.installOwnedMember4();
  install_rtc_sctp_transport.installConstructorBacklink();
  install_rtc_sctp_transport.installTag();
  install_rtc_rtp_transceiver.installOwnedMember0();
  install_rtc_rtp_transceiver.installOwnedMember1();
  install_rtc_rtp_transceiver.installOwnedMember2();
  install_rtc_rtp_transceiver.installOwnedMember3();
  install_rtc_rtp_transceiver.installOwnedMember4();
  install_rtc_rtp_transceiver.installOwnedMember5();
  install_rtc_rtp_transceiver.installOwnedMember6();
  install_rtc_rtp_transceiver.installOwnedMember7();
  install_rtc_rtp_transceiver.installOwnedMember8();
  install_rtc_rtp_transceiver.installOwnedMember9();
  install_rtc_rtp_transceiver.installOwnedMember10();
  install_rtc_rtp_transceiver.installConstructorBacklink();
  install_rtc_rtp_transceiver.installTag();
  install_rtc_rtp_sender.installOwnedMember0();
  install_rtc_rtp_sender.installOwnedMember1();
  install_rtc_rtp_sender.installOwnedMember2();
  install_rtc_rtp_sender.installOwnedMember3();
  install_rtc_rtp_sender.installOwnedMember4();
  install_rtc_rtp_sender.installOwnedMember5();
  install_rtc_rtp_sender.installOwnedMember6();
  install_rtc_rtp_sender.installOwnedMember7();
  install_rtc_rtp_sender.installOwnedMember8();
  install_rtc_rtp_sender.installOwnedMember9();
  install_rtc_rtp_sender.installOwnedMember10();
  install_rtc_rtp_sender.installConstructorBacklink();
  install_rtc_rtp_sender.installTag();
  install_rtc_rtp_receiver.installOwnedMember0();
  install_rtc_rtp_receiver.installOwnedMember1();
  install_rtc_rtp_receiver.installOwnedMember2();
  install_rtc_rtp_receiver.installOwnedMember3();
  install_rtc_rtp_receiver.installOwnedMember4();
  install_rtc_rtp_receiver.installOwnedMember5();
  install_rtc_rtp_receiver.installOwnedMember6();
  install_rtc_rtp_receiver.installOwnedMember7();
  install_rtc_rtp_receiver.installOwnedMember8();
  install_rtc_rtp_receiver.installOwnedMember9();
  install_rtc_rtp_receiver.installOwnedMember10();
  install_rtc_rtp_receiver.installConstructorBacklink();
  install_rtc_rtp_receiver.installTag();
  install_rtc_peer_connection_ice_event_candidate_property();
  install_rtc_peer_connection_ice_event.installConstructorBacklink();
  install_rtc_peer_connection_ice_event.installTag();
  install_rtc_peer_connection_ice_error_event_address_property();
  install_rtc_peer_connection_ice_error_event_port_property();
  install_rtc_peer_connection_ice_error_event_host_candidate_property();
  install_rtc_peer_connection_ice_error_event_url_property();
  install_rtc_peer_connection_ice_error_event_error_code_property();
  install_rtc_peer_connection_ice_error_event_error_text_property();
  install_rtc_peer_connection_ice_error_event.installConstructorBacklink();
  install_rtc_peer_connection_ice_error_event.installTag();
  install_rtc_peer_connection.installOwnedMember0();
  install_rtc_peer_connection.installOwnedMember1();
  install_rtc_peer_connection.installOwnedMember2();
  install_rtc_peer_connection.installOwnedMember3();
  install_rtc_peer_connection.installOwnedMember4();
  install_rtc_peer_connection.installOwnedMember5();
  install_rtc_peer_connection.installOwnedMember6();
  install_rtc_peer_connection.installOwnedMember7();
  install_rtc_peer_connection.installOwnedMember8();
  install_rtc_peer_connection.installOwnedMember9();
  install_rtc_peer_connection.installOwnedMember10();
  install_rtc_peer_connection.installOwnedMember11();
  install_rtc_peer_connection.installOwnedMember12();
  install_rtc_peer_connection.installOwnedMember13();
  install_rtc_peer_connection.installOwnedMember14();
  install_rtc_peer_connection.installOwnedMember15();
  install_rtc_peer_connection.installOwnedMember16();
  install_rtc_peer_connection.installOwnedMember17();
  install_rtc_peer_connection.installOwnedMember18();
  install_rtc_peer_connection.installOwnedMember19();
  install_rtc_peer_connection.installOwnedMember20();
  install_rtc_peer_connection.installOwnedMember21();
  install_rtc_peer_connection.installOwnedMember22();
  install_rtc_peer_connection.installOwnedMember23();
  install_rtc_peer_connection.installOwnedMember24();
  install_rtc_peer_connection.installOwnedMember25();
  install_rtc_peer_connection.installOwnedMember26();
  install_rtc_peer_connection.installOwnedMember27();
  install_rtc_peer_connection.installOwnedMember28();
  install_rtc_peer_connection.installOwnedMember29();
  install_rtc_peer_connection.installOwnedMember30();
  install_rtc_peer_connection.installOwnedMember31();
  install_rtc_peer_connection.installOwnedMember32();
  install_rtc_peer_connection.installOwnedMember33();
  install_rtc_peer_connection.installOwnedMember34();
  install_rtc_peer_connection.installOwnedMember35();
  install_rtc_peer_connection.installOwnedMember36();
  install_rtc_peer_connection.installOwnedMember37();
  install_rtc_peer_connection.installOwnedMember38();
  install_rtc_peer_connection.installOwnedMember39();
  install_rtc_peer_connection.installOwnedMember40();
  install_rtc_peer_connection.installOwnedMember41();
  install_rtc_peer_connection.installOwnedMember42();
  install_rtc_peer_connection.installOwnedMember43();
  install_rtc_peer_connection.installOwnedMember44();
  install_rtc_peer_connection.installConstructorBacklink();
  install_rtc_peer_connection.installTag();
  install_rtc_ice_transport.installOwnedMember0();
  install_rtc_ice_transport.installOwnedMember1();
  install_rtc_ice_transport.installOwnedMember2();
  install_rtc_ice_transport.installOwnedMember3();
  install_rtc_ice_transport.installOwnedMember4();
  install_rtc_ice_transport.installOwnedMember5();
  install_rtc_ice_transport.installOwnedMember6();
  install_rtc_ice_transport.installOwnedMember7();
  install_rtc_ice_transport.installOwnedMember8();
  install_rtc_ice_transport.installOwnedMember9();
  install_rtc_ice_transport.installOwnedMember10();
  install_rtc_ice_transport.installConstructorBacklink();
  install_rtc_ice_transport.installTag();
  install_rtc_ice_candidate.installOwnedMember0();
  install_rtc_ice_candidate.installOwnedMember1();
  install_rtc_ice_candidate.installOwnedMember2();
  install_rtc_ice_candidate.installOwnedMember3();
  install_rtc_ice_candidate.installOwnedMember4();
  install_rtc_ice_candidate.installOwnedMember5();
  install_rtc_ice_candidate.installOwnedMember6();
  install_rtc_ice_candidate.installOwnedMember7();
  install_rtc_ice_candidate.installOwnedMember8();
  install_rtc_ice_candidate.installOwnedMember9();
  install_rtc_ice_candidate.installOwnedMember10();
  install_rtc_ice_candidate.installOwnedMember11();
  install_rtc_ice_candidate.installOwnedMember12();
  install_rtc_ice_candidate.installOwnedMember13();
  install_rtc_ice_candidate.installOwnedMember14();
  install_rtc_ice_candidate.installOwnedMember15();
  install_rtc_ice_candidate.installOwnedMember16();
  install_rtc_ice_candidate.installConstructorBacklink();
  install_rtc_ice_candidate.installTag();
  install_rtc_error_event_error_property();
  install_rtc_error_event.installConstructorBacklink();
  install_rtc_error_event.installTag();
  install_rtc_error.installOwnedMember0();
  install_rtc_error.installOwnedMember1();
  install_rtc_error.installOwnedMember2();
  install_rtc_error.installOwnedMember3();
  install_rtc_error.installOwnedMember4();
  install_rtc_error.installOwnedMember5();
  install_rtc_error.installConstructorBacklink();
  install_rtc_error.installTag();
  install_rtc_encoded_video_frame.installOwnedMember0();
  install_rtc_encoded_video_frame.installOwnedMember1();
  install_rtc_encoded_video_frame.installOwnedMember2();
  install_rtc_encoded_video_frame.installOwnedMember3();
  install_rtc_encoded_video_frame.installOwnedMember4();
  install_rtc_encoded_video_frame.installConstructorBacklink();
  install_rtc_encoded_video_frame.installTag();
  install_rtc_encoded_audio_frame.installOwnedMember0();
  install_rtc_encoded_audio_frame.installOwnedMember1();
  install_rtc_encoded_audio_frame.installOwnedMember2();
  install_rtc_encoded_audio_frame.installOwnedMember3();
  install_rtc_encoded_audio_frame.installConstructorBacklink();
  install_rtc_encoded_audio_frame.installTag();
  install_rtc_dtls_transport.installOwnedMember0();
  install_rtc_dtls_transport.installOwnedMember1();
  install_rtc_dtls_transport.installOwnedMember2();
  install_rtc_dtls_transport.installOwnedMember3();
  install_rtc_dtls_transport.installOwnedMember4();
  install_rtc_dtls_transport.installConstructorBacklink();
  install_rtc_dtls_transport.installTag();
  install_rtc_data_channel_event_channel_property();
  install_rtc_data_channel_event.installConstructorBacklink();
  install_rtc_data_channel_event.installTag();
  install_rtc_dtmf_tone_change_event_tone_property();
  install_rtc_dtmf_tone_change_event.installConstructorBacklink();
  install_rtc_dtmf_tone_change_event.installTag();
  install_rtc_dtmf_sender.installOwnedMember0();
  install_rtc_dtmf_sender.installOwnedMember1();
  install_rtc_dtmf_sender.installOwnedMember2();
  install_rtc_dtmf_sender.installOwnedMember3();
  install_rtc_dtmf_sender.installConstructorBacklink();
  install_rtc_dtmf_sender.installTag();
  install_rtc_certificate.installOwnedMember0();
  install_rtc_certificate.installOwnedMember1();
  install_rtc_certificate.installConstructorBacklink();
  install_rtc_certificate.installTag();
  install_rtc_data_channel.installOwnedMember0();
  install_rtc_data_channel.installOwnedMember1();
  install_rtc_data_channel.installOwnedMember2();
  install_rtc_data_channel.installOwnedMember3();
  install_rtc_data_channel.installOwnedMember4();
  install_rtc_data_channel.installOwnedMember5();
  install_rtc_data_channel.installOwnedMember6();
  install_rtc_data_channel.installOwnedMember7();
  install_rtc_data_channel.installOwnedMember8();
  install_rtc_data_channel.installOwnedMember9();
  install_rtc_data_channel.installOwnedMember10();
  install_rtc_data_channel.installOwnedMember11();
  install_rtc_data_channel.installOwnedMember12();
  install_rtc_data_channel.installOwnedMember13();
  install_rtc_data_channel.installOwnedMember14();
  install_rtc_data_channel.installOwnedMember15();
  install_rtc_data_channel.installOwnedMember16();
  install_rtc_data_channel.installOwnedMember17();
  install_rtc_data_channel.installOwnedMember18();
  install_rtc_data_channel.installOwnedMember19();
  install_rtc_data_channel.installConstructorBacklink();
  install_rtc_data_channel.installTag();
  install_rtc_rtp_script_transform.installConstructorBacklink();
  install_rtc_rtp_script_transform.installTag();
  install_webkit_rtc_peer_connection.installGlobal();
  installDispatchedStaticMethod(
    webrtcRuntime.RTCPeerConnection,
    "generateCertificate",
    webrtcRuntime.generateCertificate,
    1,
  );
  installDispatchedStaticMethod(
    webrtcRuntime.RTCRtpSender,
    "getCapabilities",
    webrtcRuntime.rtpCapabilities,
    1,
  );
  installDispatchedStaticMethod(
    webrtcRuntime.RTCRtpReceiver,
    "getCapabilities",
    webrtcRuntime.rtpCapabilities,
    1,
  );
}
