import * as install_analyser_node from "../api/audio/members/analyser-node.js";
import * as install_audio_buffer_source_node from "../api/audio/members/audio-buffer-source-node.js";
import * as install_audio_buffer from "../api/audio/members/audio-buffer.js";
import * as install_audio_context from "../api/audio/members/audio-context.js";
import * as install_audio_destination_node from "../api/audio/members/audio-destination-node.js";
import * as install_audio_listener from "../api/audio/members/audio-listener.js";
import * as install_audio_node from "../api/audio/members/audio-node.js";
import * as install_audio_param_map from "../api/audio/members/audio-param-map.js";
import * as install_audio_param from "../api/audio/members/audio-param.js";
import * as install_audio_playback_stats from "../api/audio/members/audio-playback-stats.js";
import * as install_audio_scheduled_source_node from "../api/audio/members/audio-scheduled-source-node.js";
import * as install_audio_sink_info from "../api/audio/members/audio-sink-info.js";
import * as install_audio_worklet_node from "../api/audio/members/audio-worklet-node.js";
import * as install_base_audio_context from "../api/audio/members/base-audio-context.js";
import * as install_biquad_filter_node from "../api/audio/members/biquad-filter-node.js";
import * as install_channel_merger_node from "../api/audio/members/channel-merger-node.js";
import * as install_channel_splitter_node from "../api/audio/members/channel-splitter-node.js";
import * as install_constant_source_node from "../api/audio/members/constant-source-node.js";
import * as install_convolver_node from "../api/audio/members/convolver-node.js";
import * as install_delay_node from "../api/audio/members/delay-node.js";
import * as install_dynamics_compressor_node from "../api/audio/members/dynamics-compressor-node.js";
import * as install_gain_node from "../api/audio/members/gain-node.js";
import * as install_iir_filter_node from "../api/audio/members/iir-filter-node.js";
import * as install_media_element_audio_source_node from "../api/audio/members/media-element-audio-source-node.js";
import * as install_media_stream_audio_destination_node from "../api/audio/members/media-stream-audio-destination-node.js";
import * as install_media_stream_audio_source_node from "../api/audio/members/media-stream-audio-source-node.js";
import { install as install_offline_audio_completion_event_rendered_buffer_property } from "../api/audio/members/offline-audio-completion-event-rendered-buffer-property.js";
import * as install_offline_audio_completion_event from "../api/audio/members/offline-audio-completion-event.js";
import * as install_offline_audio_context from "../api/audio/members/offline-audio-context.js";
import * as install_oscillator_node from "../api/audio/members/oscillator-node.js";
import * as install_panner_node from "../api/audio/members/panner-node.js";
import * as install_periodic_wave from "../api/audio/members/periodic-wave.js";
import * as install_script_processor_node from "../api/audio/members/script-processor-node.js";
import * as install_stereo_panner_node from "../api/audio/members/stereo-panner-node.js";
import * as install_wave_shaper_node from "../api/audio/members/wave-shaper-node.js";

export function installAudio() {
  install_base_audio_context.installGlobal();
  install_audio_context.installGlobal();
  install_offline_audio_context.installGlobal();
  install_audio_buffer.installGlobal();
  install_audio_node.installGlobal();
  install_audio_destination_node.installGlobal();
  install_audio_listener.installGlobal();
  install_audio_param.installGlobal();
  install_audio_scheduled_source_node.installGlobal();
  install_audio_buffer_source_node.installGlobal();
  install_audio_worklet_node.installGlobal();
  install_media_element_audio_source_node.installGlobal();
  install_media_stream_audio_source_node.installGlobal();
  install_media_stream_audio_destination_node.installGlobal();
  install_audio_param_map.installGlobal();
  install_audio_sink_info.installGlobal();
  install_audio_playback_stats.installGlobal();
  install_offline_audio_completion_event.installGlobal();
  install_analyser_node.installGlobal();
  install_biquad_filter_node.installGlobal();
  install_channel_merger_node.installGlobal();
  install_channel_splitter_node.installGlobal();
  install_constant_source_node.installGlobal();
  install_convolver_node.installGlobal();
  install_delay_node.installGlobal();
  install_dynamics_compressor_node.installGlobal();
  install_gain_node.installGlobal();
  install_iir_filter_node.installGlobal();
  install_oscillator_node.installGlobal();
  install_panner_node.installGlobal();
  install_periodic_wave.installGlobal();
  install_script_processor_node.installGlobal();
  install_stereo_panner_node.installGlobal();
  install_wave_shaper_node.installGlobal();
  install_base_audio_context.installRelation();
  install_audio_context.installRelation();
  install_offline_audio_context.installRelation();
  install_audio_buffer.installRelation();
  install_audio_node.installRelation();
  install_audio_destination_node.installRelation();
  install_audio_listener.installRelation();
  install_audio_param.installRelation();
  install_audio_scheduled_source_node.installRelation();
  install_audio_buffer_source_node.installRelation();
  install_audio_worklet_node.installRelation();
  install_media_element_audio_source_node.installRelation();
  install_media_stream_audio_source_node.installRelation();
  install_media_stream_audio_destination_node.installRelation();
  install_audio_param_map.installRelation();
  install_audio_sink_info.installRelation();
  install_audio_playback_stats.installRelation();
  install_offline_audio_completion_event.installRelation();
  install_analyser_node.installRelation();
  install_biquad_filter_node.installRelation();
  install_channel_merger_node.installRelation();
  install_channel_splitter_node.installRelation();
  install_constant_source_node.installRelation();
  install_convolver_node.installRelation();
  install_delay_node.installRelation();
  install_dynamics_compressor_node.installRelation();
  install_gain_node.installRelation();
  install_iir_filter_node.installRelation();
  install_oscillator_node.installRelation();
  install_panner_node.installRelation();
  install_periodic_wave.installRelation();
  install_script_processor_node.installRelation();
  install_stereo_panner_node.installRelation();
  install_wave_shaper_node.installRelation();
  install_base_audio_context.installOwnedMember0();
  install_base_audio_context.installOwnedMember1();
  install_base_audio_context.installOwnedMember2();
  install_base_audio_context.installOwnedMember3();
  install_base_audio_context.installOwnedMember4();
  install_base_audio_context.installOwnedMember5();
  install_base_audio_context.installOwnedMember6();
  install_base_audio_context.installOwnedMember7();
  install_base_audio_context.installOwnedMember8();
  install_base_audio_context.installOwnedMember9();
  install_base_audio_context.installOwnedMember10();
  install_base_audio_context.installOwnedMember11();
  install_base_audio_context.installOwnedMember12();
  install_base_audio_context.installOwnedMember13();
  install_base_audio_context.installOwnedMember14();
  install_base_audio_context.installOwnedMember15();
  install_base_audio_context.installOwnedMember16();
  install_base_audio_context.installOwnedMember17();
  install_base_audio_context.installOwnedMember18();
  install_base_audio_context.installOwnedMember19();
  install_base_audio_context.installOwnedMember20();
  install_base_audio_context.installOwnedMember21();
  install_base_audio_context.installOwnedMember22();
  install_base_audio_context.installOwnedMember23();
  install_base_audio_context.installOwnedMember24();
  install_base_audio_context.installConstructorBacklink();
  install_base_audio_context.installOwnedMember25();
  install_base_audio_context.installTag();
  install_audio_context.installOwnedMember0();
  install_audio_context.installOwnedMember1();
  install_audio_context.installOwnedMember2();
  install_audio_context.installOwnedMember3();
  install_audio_context.installOwnedMember4();
  install_audio_context.installOwnedMember5();
  install_audio_context.installOwnedMember6();
  install_audio_context.installOwnedMember7();
  install_audio_context.installOwnedMember8();
  install_audio_context.installOwnedMember9();
  install_audio_context.installOwnedMember10();
  install_audio_context.installConstructorBacklink();
  install_audio_context.installOwnedMember11();
  install_audio_context.installOwnedMember12();
  install_audio_context.installOwnedMember13();
  install_audio_context.installTag();
  install_offline_audio_context.installOwnedMember0();
  install_offline_audio_context.installOwnedMember1();
  install_offline_audio_context.installOwnedMember2();
  install_offline_audio_context.installOwnedMember3();
  install_offline_audio_context.installOwnedMember4();
  install_offline_audio_context.installConstructorBacklink();
  install_offline_audio_context.installTag();
  install_audio_buffer.installOwnedMember0();
  install_audio_buffer.installOwnedMember1();
  install_audio_buffer.installOwnedMember2();
  install_audio_buffer.installOwnedMember3();
  install_audio_buffer.installOwnedMember4();
  install_audio_buffer.installOwnedMember5();
  install_audio_buffer.installOwnedMember6();
  install_audio_buffer.installConstructorBacklink();
  install_audio_buffer.installTag();
  install_audio_node.installOwnedMember0();
  install_audio_node.installOwnedMember1();
  install_audio_node.installOwnedMember2();
  install_audio_node.installOwnedMember3();
  install_audio_node.installOwnedMember4();
  install_audio_node.installOwnedMember5();
  install_audio_node.installOwnedMember6();
  install_audio_node.installOwnedMember7();
  install_audio_node.installConstructorBacklink();
  install_audio_node.installTag();
  install_audio_destination_node.installOwnedMember0();
  install_audio_destination_node.installConstructorBacklink();
  install_audio_destination_node.installTag();
  install_audio_listener.installOwnedMember0();
  install_audio_listener.installOwnedMember1();
  install_audio_listener.installOwnedMember2();
  install_audio_listener.installOwnedMember3();
  install_audio_listener.installOwnedMember4();
  install_audio_listener.installOwnedMember5();
  install_audio_listener.installOwnedMember6();
  install_audio_listener.installOwnedMember7();
  install_audio_listener.installOwnedMember8();
  install_audio_listener.installOwnedMember9();
  install_audio_listener.installOwnedMember10();
  install_audio_listener.installConstructorBacklink();
  install_audio_listener.installTag();
  install_audio_param.installOwnedMember0();
  install_audio_param.installOwnedMember1();
  install_audio_param.installOwnedMember2();
  install_audio_param.installOwnedMember3();
  install_audio_param.installOwnedMember4();
  install_audio_param.installOwnedMember5();
  install_audio_param.installOwnedMember6();
  install_audio_param.installOwnedMember7();
  install_audio_param.installOwnedMember8();
  install_audio_param.installOwnedMember9();
  install_audio_param.installOwnedMember10();
  install_audio_param.installOwnedMember11();
  install_audio_param.installConstructorBacklink();
  install_audio_param.installTag();
  install_audio_scheduled_source_node.installOwnedMember0();
  install_audio_scheduled_source_node.installOwnedMember1();
  install_audio_scheduled_source_node.installOwnedMember2();
  install_audio_scheduled_source_node.installConstructorBacklink();
  install_audio_scheduled_source_node.installTag();
  install_audio_buffer_source_node.installOwnedMember0();
  install_audio_buffer_source_node.installOwnedMember1();
  install_audio_buffer_source_node.installOwnedMember2();
  install_audio_buffer_source_node.installOwnedMember3();
  install_audio_buffer_source_node.installOwnedMember4();
  install_audio_buffer_source_node.installOwnedMember5();
  install_audio_buffer_source_node.installOwnedMember6();
  install_audio_buffer_source_node.installConstructorBacklink();
  install_audio_buffer_source_node.installTag();
  install_audio_worklet_node.installOwnedMember0();
  install_audio_worklet_node.installOwnedMember1();
  install_audio_worklet_node.installOwnedMember2();
  install_audio_worklet_node.installConstructorBacklink();
  install_audio_worklet_node.installTag();
  install_media_element_audio_source_node.installOwnedMember0();
  install_media_element_audio_source_node.installConstructorBacklink();
  install_media_element_audio_source_node.installTag();
  install_media_stream_audio_source_node.installOwnedMember0();
  install_media_stream_audio_source_node.installConstructorBacklink();
  install_media_stream_audio_source_node.installTag();
  install_media_stream_audio_destination_node.installOwnedMember0();
  install_media_stream_audio_destination_node.installConstructorBacklink();
  install_media_stream_audio_destination_node.installTag();
  install_audio_param_map.installOwnedMember0();
  install_audio_param_map.installOwnedMember1();
  install_audio_param_map.installOwnedMember2();
  install_audio_param_map.installOwnedMember3();
  install_audio_param_map.installOwnedMember4();
  install_audio_param_map.installOwnedMember5();
  install_audio_param_map.installOwnedMember6();
  install_audio_param_map.installConstructorBacklink();
  install_audio_param_map.installTag();
  install_audio_param_map.installIterator();
  install_audio_sink_info.installOwnedMember0();
  install_audio_sink_info.installConstructorBacklink();
  install_audio_sink_info.installTag();
  install_audio_playback_stats.installOwnedMember0();
  install_audio_playback_stats.installOwnedMember1();
  install_audio_playback_stats.installOwnedMember2();
  install_audio_playback_stats.installOwnedMember3();
  install_audio_playback_stats.installOwnedMember4();
  install_audio_playback_stats.installOwnedMember5();
  install_audio_playback_stats.installOwnedMember6();
  install_audio_playback_stats.installOwnedMember7();
  install_audio_playback_stats.installConstructorBacklink();
  install_audio_playback_stats.installTag();
  install_offline_audio_completion_event_rendered_buffer_property();
  install_offline_audio_completion_event.installConstructorBacklink();
  install_offline_audio_completion_event.installTag();
  install_analyser_node.installOwnedMember0();
  install_analyser_node.installOwnedMember1();
  install_analyser_node.installOwnedMember2();
  install_analyser_node.installOwnedMember3();
  install_analyser_node.installOwnedMember4();
  install_analyser_node.installOwnedMember5();
  install_analyser_node.installOwnedMember6();
  install_analyser_node.installOwnedMember7();
  install_analyser_node.installOwnedMember8();
  install_analyser_node.installConstructorBacklink();
  install_analyser_node.installTag();
  install_biquad_filter_node.installOwnedMember0();
  install_biquad_filter_node.installOwnedMember1();
  install_biquad_filter_node.installOwnedMember2();
  install_biquad_filter_node.installOwnedMember3();
  install_biquad_filter_node.installOwnedMember4();
  install_biquad_filter_node.installOwnedMember5();
  install_biquad_filter_node.installConstructorBacklink();
  install_biquad_filter_node.installTag();
  install_channel_merger_node.installConstructorBacklink();
  install_channel_merger_node.installTag();
  install_channel_splitter_node.installConstructorBacklink();
  install_channel_splitter_node.installTag();
  install_constant_source_node.installOwnedMember0();
  install_constant_source_node.installConstructorBacklink();
  install_constant_source_node.installTag();
  install_convolver_node.installOwnedMember0();
  install_convolver_node.installOwnedMember1();
  install_convolver_node.installConstructorBacklink();
  install_convolver_node.installTag();
  install_delay_node.installOwnedMember0();
  install_delay_node.installConstructorBacklink();
  install_delay_node.installTag();
  install_dynamics_compressor_node.installOwnedMember0();
  install_dynamics_compressor_node.installOwnedMember1();
  install_dynamics_compressor_node.installOwnedMember2();
  install_dynamics_compressor_node.installOwnedMember3();
  install_dynamics_compressor_node.installOwnedMember4();
  install_dynamics_compressor_node.installOwnedMember5();
  install_dynamics_compressor_node.installConstructorBacklink();
  install_dynamics_compressor_node.installTag();
  install_gain_node.installOwnedMember0();
  install_gain_node.installConstructorBacklink();
  install_gain_node.installTag();
  install_iir_filter_node.installOwnedMember0();
  install_iir_filter_node.installConstructorBacklink();
  install_iir_filter_node.installTag();
  install_oscillator_node.installOwnedMember0();
  install_oscillator_node.installOwnedMember1();
  install_oscillator_node.installOwnedMember2();
  install_oscillator_node.installOwnedMember3();
  install_oscillator_node.installConstructorBacklink();
  install_oscillator_node.installTag();
  install_panner_node.installOwnedMember0();
  install_panner_node.installOwnedMember1();
  install_panner_node.installOwnedMember2();
  install_panner_node.installOwnedMember3();
  install_panner_node.installOwnedMember4();
  install_panner_node.installOwnedMember5();
  install_panner_node.installOwnedMember6();
  install_panner_node.installOwnedMember7();
  install_panner_node.installOwnedMember8();
  install_panner_node.installOwnedMember9();
  install_panner_node.installOwnedMember10();
  install_panner_node.installOwnedMember11();
  install_panner_node.installOwnedMember12();
  install_panner_node.installOwnedMember13();
  install_panner_node.installOwnedMember14();
  install_panner_node.installOwnedMember15();
  install_panner_node.installConstructorBacklink();
  install_panner_node.installTag();
  install_periodic_wave.installConstructorBacklink();
  install_periodic_wave.installTag();
  install_script_processor_node.installOwnedMember0();
  install_script_processor_node.installOwnedMember1();
  install_script_processor_node.installConstructorBacklink();
  install_script_processor_node.installTag();
  install_stereo_panner_node.installOwnedMember0();
  install_stereo_panner_node.installConstructorBacklink();
  install_stereo_panner_node.installTag();
  install_wave_shaper_node.installOwnedMember0();
  install_wave_shaper_node.installOwnedMember1();
  install_wave_shaper_node.installConstructorBacklink();
  install_wave_shaper_node.installTag();
}
